Repository emil476m/GameBase, pull requests merged in 2025-04, with the labels that each got.

#7 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#9 Gateway/feat/setup
  Apps/SearchEngine/api/controllers/SearchEngineController.cs
  Apps/gateway/.dockerignore
  Apps/gateway/Dockerfile
  Apps/gateway/gateway.sln
  Apps/gateway/src/Program.cs
  Apps/gateway/src/Properties/launchSettings.json
  Apps/gateway/src/appsettings.Development.json
  Apps/gateway/src/appsettings.json
  Apps/gateway/src/configs/ocelot.global.json
  Apps/gateway/src/configs/ocelot.search_engine-service.json
  Apps/gateway/src/src.csproj
  docker-compose.yml
Labels: enhancement

#10 Game base/feature/create service
  Apps/CreateService/.dockerignore
  Apps/CreateService/CreateService.sln
  Apps/CreateService/Dockerfile
  Apps/CreateService/api/Program.cs
  Apps/CreateService/api/Properties/launchSettings.json
  Apps/CreateService/api/api.csproj
  Apps/CreateService/api/api.http
  Apps/CreateService/api/appsettings.Development.json
  Apps/CreateService/api/appsettings.json
  Apps/CreateService/api/controllers/CreateController.cs
  Apps/CreateService/infrastructure/Implementations/Repository.cs
  Apps/CreateService/infrastructure/Interfaces/IRepository.cs
  Apps/CreateService/infrastructure/Mappers/GameMapper.cs
  Apps/CreateService/infrastructure/Models/GameDbModel.cs
  Apps/CreateService/infrastructure/Models/GameModel.cs
  Apps/CreateService/infrastructure/infrastructure.csproj
  Apps/CreateService/service/Implementations/CreateService.cs
  Apps/CreateService/service/Interfaces/IService.cs
  Apps/CreateService/service/service.csproj
  Apps/gateway/src/Program.cs
  Apps/gateway/src/configs/ocelot.create_service.json
  docker-compose.yml
  scripts/shell/sql-set-up.sh
  scripts/sql/Create.sql
  scripts/sql/MockData.sql
Labels: enhancement

#12 fixed bug
  Apps/CreateService/infrastructure/Models/GameModel.cs
  scripts/shell/sql-set-up.sh
Labels: bug

#17 Search engine/feat/return games
  Apps/SearchEngine/api/Program.cs
  Apps/SearchEngine/api/controllers/SearchEngineController.cs
  Apps/SearchEngine/infrastructur/Implementation/SearchRepositorySearchDto.cs
  Apps/SearchEngine/infrastructur/Implementation/SeartchRepositoryString.cs
  Apps/SearchEngine/infrastructur/Interfaces/ISearchRepository.cs
  Apps/SearchEngine/infrastructur/Models/Internals/GameEntity.cs
  Apps/SearchEngine/infrastructur/Models/Internals/SearchEntity.cs
  Apps/SearchEngine/infrastructur/Models/Mappers/GameMapper.cs
  Apps/SearchEngine/infrastructur/Models/Mappers/SearchMapper.cs
  Apps/SearchEngine/infrastructur/Models/externals/GameDto.cs
  Apps/SearchEngine/infrastructur/Models/externals/SearchDto.cs
  Apps/SearchEngine/service/Implementations/ServiceSearchDto.cs
  Apps/SearchEngine/service/Implementations/ServiceString.cs
  Apps/SearchEngine/service/Interfaces/IService.cs
  Apps/gateway/src/configuration/ocelot.global.json
Labels: enhancement

#19 Create auto-deploy.yml
  .github/workflows/auto-deploy.yml
Labels: enhancement

#20 Feat/deploy
  .github/workflows/auto-deploy.yml
  compose-live.yml
  docker-compose.yml
Labels: enhancement

#21 Create service/hotfix/review during creation
  Apps/CreateService/api/controllers/CreateController.cs
  Apps/CreateService/infrastructure/Implementations/Repository.cs
  Apps/CreateService/infrastructure/Models/GameCreateModelDto.cs
  Apps/CreateService/service/Implementations/CreateService.cs
  Apps/CreateService/service/Interfaces/IService.cs
Labels: bug, enhancement

#22 feature hub init set up
  compose-live.yml
  docker-compose.yml
Labels: enhancement

#24 added load balencing for background services
  compose-live.yml
Labels: enhancement

#26 updated auto-deploy.yml with new envirements
  .github/workflows/auto-deploy.yml
Labels: bug

#27 remowed spaceing causing issues
  docker-compose.yml
Labels: bug

#28 added restart always to docker compose file
  docker-compose.yml
Labels: bug

#29 Search engine/feat/pageenisation
  Apps/SearchEngine/api/controllers/SearchEngineController.cs
  Apps/SearchEngine/infrastructur/Implementation/SearchRepositorySearchDto.cs
  Apps/SearchEngine/infrastructur/Interfaces/ISearchRepository.cs
  Apps/SearchEngine/infrastructur/Models/Internals/GameEntity.cs
  Apps/SearchEngine/infrastructur/Models/Mappers/GameMapper.cs
  Apps/SearchEngine/infrastructur/Models/externals/GameDto.cs
  Apps/SearchEngine/service/Implementations/ServiceSearchDto.cs
  Apps/SearchEngine/service/Interfaces/IService.cs
  Apps/gateway/src/configuration/ocelot.global.json
Labels: enhancement, Feature request

#30 Review/feat/review dto update
  Apps/reviewHandler/api/Program.cs
  Apps/reviewHandler/api/controllers/ReviewController.cs
  Apps/reviewHandler/infrastructur/Implementations/RepositoryReviewModel.cs
  Apps/reviewHandler/infrastructur/Models/Internal/ReviewEntity.cs
  Apps/reviewHandler/infrastructur/Models/Mapper/ReviewMapper.cs
  Apps/reviewHandler/infrastructur/Models/domain/Review.cs
  Apps/reviewHandler/service/Implementations/ServiceReviewDto.cs
  scripts/sql/MockData.sql
Labels: bug, enhancement, Feature request

#32 Feat/switch to compose live
  .github/workflows/auto-deploy.yml
Labels: bug, enhancement

#33 Feat/switch to compose live
  .github/workflows/auto-deploy.yml
  compose-live.yml
Labels: bug

#34 Gate way/feat/cors
  Apps/gateway/src/Program.cs
  docker-compose.yml
Labels: bug, enhancement

#35 remowed recerved ports from gateway
  docker-compose.yml
Labels: bug

#38 Feat/basic frontend
  Apps/frontend/src/app/CreateGamePage/createGamePage.html
  Apps/frontend/src/app/Models/CreateReviewDto.ts
  Apps/frontend/src/app/Models/ReviewDto.ts
  Apps/frontend/src/app/detailedGamePage/detailedGamePage.html
  Apps/frontend/src/app/detailedGamePage/detailedGamePage.ts
  Apps/frontend/src/app/home-page/home-page.ts
Labels: bug, enhancement

#39 reduced lose cors policy
  Apps/gateway/src/Program.cs
Labels: bug

#40 Fix AI query
  Apps/frontend/src/app/CreateGamePage/createGamePage.ts
  Apps/frontend/src/app/Models/AiQuery.ts
Labels: bug

#41 Revert "Fix AI query"
  Apps/frontend/src/app/CreateGamePage/createGamePage.ts
  Apps/frontend/src/app/Models/AiQuery.ts
Labels: bug

#44 Cors/fix/wide spred cors violation
  Apps/gateway/src/Program.cs
  scripts/shell/sql-set-up.sh
Labels: bug

#43 Feat/fix ai response
  .github/workflows/auto-deploy.yml
  Apps/frontend/src/app/CreateGamePage/createGamePage.html
  Apps/frontend/src/app/CreateGamePage/createGamePage.ts
  Apps/frontend/src/app/Models/AiQuery.ts
Labels: bug
